extends:
  - eslint:recommended
  - google
parserOptions:
  ecmaVersion: 8
env:
  node: true
globals:
  Promise: true
rules:
  object-curly-spacing:
    - error
    - always
  new-cap: 0
  comma-dangle:
    - error
    - never
  no-console: 0
  max-len: 0
  prefer-rest-params: 0
