harnessApiVersion: '1.0'
type: BASIC
concurrencyStrategy: INFRA
envName: Development
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - aCQkr7DHRDGyDOHs4R8HjQ
phases:
- type: SSH
  computeProviderName: Macbook Pro
  daemonSet: false
  infraDefinitionName: Macbook Pro Docker Engine
  name: Phase 1
  phaseSteps:
  - type: INFRASTRUCTURE_NODE
    name: Prepare Infra
    steps:
    - type: DC_NODE_SELECT
      name: Select Nodes
      properties:
        excludeSelectedHostsFromFuturePhases: true
        instanceCount: 1
        specificHosts: false
    stepsInParallel: false
  - type: DISABLE_SERVICE
    name: Disable Service
    steps:
    - type: SHELL_SCRIPT
      name: Shell Script
      properties:
        commandPath: /tmp
        connectionAttributes: null
        connectionType: SSH
        executeOnDelegate: false
        host: host.docker.internal
        outputVars: ''
        publishAsVar: false
        scriptString: /usr/local/bin/docker stop math-service-development || true
        scriptType: BASH
        sshKeyRef: hohjKf-jRGu4DluYX-4H_w
        sweepingOutputName: null
        sweepingOutputScope: null
        templateExpressions: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeoutMillis: 60000
    stepsInParallel: false
  - type: DEPLOY_SERVICE
    name: Deploy Service
    steps:
    - type: SHELL_SCRIPT
      name: Shell Script
      properties:
        commandPath: /tmp
        connectionAttributes: null
        connectionType: SSH
        executeOnDelegate: false
        host: host.docker.internal
        outputVars: ''
        publishAsVar: false
        scriptString: /usr/local/bin/docker run --name math-service-development -p 8080:8080 --rm -d dwoodward/math-service:development
        scriptType: BASH
        sshKeyRef: hohjKf-jRGu4DluYX-4H_w
        sweepingOutputName: null
        sweepingOutputScope: null
        templateExpressions: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeoutMillis: 60000
    stepsInParallel: false
  - type: ENABLE_SERVICE
    name: Enable Service
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Development Docker Image
  statefulSet: false
preDeploymentSteps:
- type: ARTIFACT_CHECK
  name: Artifact Check
rollbackPhases:
- type: SSH
  computeProviderName: Macbook Pro
  daemonSet: false
  infraDefinitionName: Macbook Pro Docker Engine
  name: Rollback Phase 1
  phaseNameForRollback: Phase 1
  phaseSteps:
  - type: DISABLE_SERVICE
    name: Disable Service
    phaseStepNameForRollback: Enable Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: STOP_SERVICE
    name: Stop Service
    phaseStepNameForRollback: Deploy Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: DEPLOY_SERVICE
    name: Deploy Service
    phaseStepNameForRollback: Deploy Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: ENABLE_SERVICE
    name: Enable Service
    phaseStepNameForRollback: Disable Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    phaseStepNameForRollback: Deploy Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: Development Docker Image
  statefulSet: false
templatized: false
